### ISSUE TITLE
InjectModuleInitializer does not work in Visual Studio 2015

### ISSUE THREAD

**Issue by killyosaur** [RockFramework/Rock.StaticDependencyInjection#1]
You may want to look into the most current version (1.4) as that one does not throw the "unknown custom metadata item kind" error in dlls compiled in Visual Studio 2015.

**Comment by killyosaur** [comment]
Apparently this still isn't working after the update, and getting the same error. Not sure what to say about that.

**Comment by bfriesen** [comment]
@killyosaur I'm unable to reproduce the error. How exactly does it fail to work? What kind of project are you using? Do you have a stack trace?

**Comment by killyosaur** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "..\packages\Rock.StaticDependencyInjection.1.1.3\tools\InjectModuleInitializer.exe "C:\Code\IT\DocumentViewer\Source\DocViewer\DrApi.Net.Http\bin\Debug\DrApi.Net.Http.dll"" exited with code 1.	DrApi.Net.Http	C:\Code\IT\DocumentViewer\Source\DocViewer\DrApi.Net.Http\DrApi.Net.Http.csproj	157	

is the error I get when trying to compile. This only happens in VS 2015 (Enterprise, Version 14.0.24720.00 Update 1)

I also get a comment about Unknown custom metadata item kind: 6. if I turn off the UseModuleInitializer (set it to false) everything compiles fine.
